# Site settings
title: folio # give your site a title
email: you@example.com # put your email address in here
# edit your site description; keep it brief
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  # the subpath of your site, e.g. /blog/
url: http://username.github.io # replace username with your github username
twitter_username: twitter_username # replace with your twitter username or delete the line
github_username:  github_username # replace with your github username

# Build settings
markdown: kramdown

kramdown:
  input: GFM

highlighter: rouge # this will cause an error on github build; you can ignore it

# Pagination
gems: [jekyll-paginate]
paginate: 15
paginate_path: "/blog/page:num/"
